import type { Metadata } from "next";
import Leftsidebar from '@/app/(root)/(component)/Leftsidebar'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lapo Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <Leftsidebar />
        {children}
      </body>
    </html>
  );
}
